#!/usr/local/sbin/charm-env python3

from charms.reactive import endpoint_from_flag

import utils


if __name__ == '__main__':
    try:
        with open('/etc/ssl/cert-manager/ca.crt') as f:
            utils.ok_cert(f.read())
    except Exception as e:
        utils.fail('ca cert not available: {}'.format(e))
        raise
