#!/usr/local/sbin/charm-env python3

from charmhelpers.core import hookenv

from charms.reactive import endpoint_from_flag

import utils


if __name__ == '__main__':
	cn = hookenv.action_get('common_name')
    certs = endpoint_from_flag('certificates.ca.available')
	if not certs:
		utils.fail('certificates not available')
    utils.ok(certs.client_certs_map[cn].key)
